//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string _mainExitApp {
            get {
                return ResourceManager.GetString("_mainExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Menu.
        /// </summary>
        public static string _mainFile {
            get {
                return ResourceManager.GetString("_mainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string _mainFileClose {
            get {
                return ResourceManager.GetString("_mainFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string _mainFileOpenFile {
            get {
                return ResourceManager.GetString("_mainFileOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string _MainMenuconnection {
            get {
                return ResourceManager.GetString("_MainMenuconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC Monitoring .
        /// </summary>
        public static string _mainWindowTitle {
            get {
                return ResourceManager.GetString("_mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize background.
        /// </summary>
        public static string BackgroundScaling {
            get {
                return ResourceManager.GetString("BackgroundScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string BtnclearLog {
            get {
                return ResourceManager.GetString("BtnclearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_emove background picture.
        /// </summary>
        public static string ClearBackground {
            get {
                return ResourceManager.GetString("ClearBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to mcu.
        /// </summary>
        public static string ConnectedMcu {
            get {
                return ResourceManager.GetString("ConnectedMcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export errors.
        /// </summary>
        public static string E_xportToCsvMenu {
            get {
                return ResourceManager.GetString("E_xportToCsvMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password to gain acces to configuration settings.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password to lock configuration settings.
        /// </summary>
        public static string EnterPasswordCreate {
            get {
                return ResourceManager.GetString("EnterPasswordCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock / Lock.
        /// </summary>
        public static string EnterPasswordMenuItem {
            get {
                return ResourceManager.GetString("EnterPasswordMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string ErrorLogWindowClearList {
            get {
                return ResourceManager.GetString("ErrorLogWindowClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize icons relative to background.
        /// </summary>
        public static string IconScaling {
            get {
                return ResourceManager.GetString("IconScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VACIE Checked by inspection company.
        /// </summary>
        public static string InspectorClearInfo {
            get {
                return ResourceManager.GetString("InspectorClearInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file.
        /// </summary>
        public static string MessageBoxSaveFileHeader {
            get {
                return ResourceManager.GetString("MessageBoxSaveFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save file: {0}.
        /// </summary>
        public static string MessageBoxSaveFileText {
            get {
                return ResourceManager.GetString("MessageBoxSaveFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to mcu.
        /// </summary>
        public static string NotConnectedMcu {
            get {
                return ResourceManager.GetString("NotConnectedMcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkChangePassword {
            get {
                return ResourceManager.GetString("OkChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKpassword {
            get {
                return ResourceManager.GetString("OKpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string OpenConnectionView {
            get {
                return ResourceManager.GetString("OpenConnectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open email window.
        /// </summary>
        public static string OpenEmailWindow {
            get {
                return ResourceManager.GetString("OpenEmailWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string PasswordEnter1 {
            get {
                return ResourceManager.GetString("PasswordEnter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again.
        /// </summary>
        public static string PasswordEnter2 {
            get {
                return ResourceManager.GetString("PasswordEnter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog will auto close once password is correct.
        /// </summary>
        public static string PasswordHelp {
            get {
                return ResourceManager.GetString("PasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reconnect.
        /// </summary>
        public static string ReconnectAll {
            get {
                return ResourceManager.GetString("ReconnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set b_ackground picture.
        /// </summary>
        public static string SetSchematicBackground {
            get {
                return ResourceManager.GetString("SetSchematicBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sure, clear log.
        /// </summary>
        public static string SureClearLog {
            get {
                return ResourceManager.GetString("SureClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic email message.
        /// </summary>
        public static string TestMode {
            get {
                return ResourceManager.GetString("TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the person who clears log:.
        /// </summary>
        public static string WhoClear {
            get {
                return ResourceManager.GetString("WhoClear", resourceCulture);
            }
        }
    }
}
