//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.UserControls.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmpDefect.
        /// </summary>
        public static string AmpDefect {
            get {
                return ResourceManager.GetString("AmpDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com1 Interface.
        /// </summary>
        public static string Com1Interface {
            get {
                return ResourceManager.GetString("Com1Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com2 Interface.
        /// </summary>
        public static string Com2Interface {
            get {
                return ResourceManager.GetString("Com2Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure on Panel Bus 1.
        /// </summary>
        public static string Dsp {
            get {
                return ResourceManager.GetString("Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of MCU WatchDog circuit.
        /// </summary>
        public static string Eeprom {
            get {
                return ResourceManager.GetString("Eeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC error input triggered from EPC 48Vdc (In/Out) error contact.
        /// </summary>
        public static string Epc {
            get {
                return ResourceManager.GetString("Epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line detected on connection to EPC error input on ESC.
        /// </summary>
        public static string EpcOpenline {
            get {
                return ResourceManager.GetString("EpcOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit detected on connection to EPC error input on ESC.
        /// </summary>
        public static string EpcShortcut {
            get {
                return ResourceManager.GetString("EpcShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 button/input expansion card error.
        /// </summary>
        public static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure detected on the Line level input (impedance) of the External input.
        /// </summary>
        public static string ExternAudioLine {
            get {
                return ResourceManager.GetString("ExternAudioLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line detected on the connection to the External audio input.
        /// </summary>
        public static string ExternAudioOpenline {
            get {
                return ResourceManager.GetString("ExternAudioOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit detected on the connection to the External audio input.
        /// </summary>
        public static string ExternAudioShortcut {
            get {
                return ResourceManager.GetString("ExternAudioShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External error activated by: ESA AMP/PSU error contact, or Redundancy Module error contact.
        /// </summary>
        public static string ExternError {
            get {
                return ResourceManager.GetString("ExternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External error activated by: ESA AMP/PSU error contact, or Redundancy Module error contact.
        /// </summary>
        public static string ExternOpenline {
            get {
                return ResourceManager.GetString("ExternOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit detected on connection to External error input on ESC.
        /// </summary>
        public static string ExternShortcut {
            get {
                return ResourceManager.GetString("ExternShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of MCU WatchDog circuit.
        /// </summary>
        public static string HwWdog {
            get {
                return ResourceManager.GetString("HwWdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load deviation found on Line A at 1kHz measurement.
        /// </summary>
        public static string ImpDev1KhzA {
            get {
                return ResourceManager.GetString("ImpDev1KhzA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load deviation found on Line B at 1kHz measurement.
        /// </summary>
        public static string ImpDev1KhzB {
            get {
                return ResourceManager.GetString("ImpDev1KhzB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load deviation found on Line A or B at 20kHz measurement.
        /// </summary>
        public static string ImpDev22Khz {
            get {
                return ResourceManager.GetString("ImpDev22Khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of 230Vac main power source.
        /// </summary>
        public static string MainPower230V {
            get {
                return ResourceManager.GetString("MainPower230V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains Fuse error activated by: ESA/EPC 230Vac error contact or (opt.) Circuit breaker error contact.
        /// </summary>
        public static string MainsFuse {
            get {
                return ResourceManager.GetString("MainsFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line detected on connection to Mains Fuse error input on ESC.
        /// </summary>
        public static string MainsFuseOpenline {
            get {
                return ResourceManager.GetString("MainsFuseOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit detected on connection to Mains Fuse error input on ESC.
        /// </summary>
        public static string MainsFuseShortcut {
            get {
                return ResourceManager.GetString("MainsFuseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line - Microphone capsule.
        /// </summary>
        public static string MicCapOpenLine {
            get {
                return ResourceManager.GetString("MicCapOpenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit - Microphone capsule.
        /// </summary>
        public static string MicCapShortcut {
            get {
                return ResourceManager.GetString("MicCapShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio connection failure on Panel Bus 1.
        /// </summary>
        public static string MicLineBus1 {
            get {
                return ResourceManager.GetString("MicLineBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio connection failure on Panel Bus 2.
        /// </summary>
        public static string MicLineBus2 {
            get {
                return ResourceManager.GetString("MicLineBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone push button not found.
        /// </summary>
        public static string MicRequest {
            get {
                return ResourceManager.GetString("MicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of SD-card 1 / MP3 track.
        /// </summary>
        public static string Mp31 {
            get {
                return ResourceManager.GetString("Mp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of SD-card 2 / MP3 track.
        /// </summary>
        public static string Mp32 {
            get {
                return ResourceManager.GetString("Mp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoBackup {
            get {
                return ResourceManager.GetString("NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line is detected on Line A.
        /// </summary>
        public static string OpenlineA {
            get {
                return ResourceManager.GetString("OpenlineA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line is detected on Line B.
        /// </summary>
        public static string OpenlineB {
            get {
                return ResourceManager.GetString("OpenlineB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of panel transmit.
        /// </summary>
        public static string PanelTxIsr {
            get {
                return ResourceManager.GetString("PanelTxIsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure on Panel Bus 1.
        /// </summary>
        public static string Rs485FpBus1 {
            get {
                return ResourceManager.GetString("Rs485FpBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure on Panel Bus 2.
        /// </summary>
        public static string Rs485FpBus2 {
            get {
                return ResourceManager.GetString("Rs485FpBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure on Unit link connection.
        /// </summary>
        public static string Rs485MasterSlave {
            get {
                return ResourceManager.GetString("Rs485MasterSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit is detected on Line A.
        /// </summary>
        public static string ShortcutA {
            get {
                return ResourceManager.GetString("ShortcutA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit is detected on Line B.
        /// </summary>
        public static string ShortcutB {
            get {
                return ResourceManager.GetString("ShortcutB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short to Earth is found on Line A or B.
        /// </summary>
        public static string ShortcutToEarth {
            get {
                return ResourceManager.GetString("ShortcutToEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure on Unit link connection.
        /// </summary>
        public static string SlaveComInterface {
            get {
                return ResourceManager.GetString("SlaveComInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital audio stream 1 failure on Unit link connection.
        /// </summary>
        public static string SlaveSpdif1 {
            get {
                return ResourceManager.GetString("SlaveSpdif1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital audio stream 2 failure on Unit link connection.
        /// </summary>
        public static string SlaveSpdif2 {
            get {
                return ResourceManager.GetString("SlaveSpdif2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entero ESC - failure of 48Vdc backup power source.
        /// </summary>
        public static string SparePower48V {
            get {
                return ResourceManager.GetString("SparePower48V", resourceCulture);
            }
        }
    }
}
