//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.UserControls.ErrorNames", typeof(ErrorNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier has an error.
        /// </summary>
        internal static string AmpDefect {
            get {
                return ResourceManager.GetString("AmpDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com1 interface issue.
        /// </summary>
        internal static string Com1Interface {
            get {
                return ResourceManager.GetString("Com1Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com2 interface issue.
        /// </summary>
        internal static string Com2Interface {
            get {
                return ResourceManager.GetString("Com2Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP error.
        /// </summary>
        internal static string Dsp {
            get {
                return ResourceManager.GetString("Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eeprom error.
        /// </summary>
        internal static string Eeprom {
            get {
                return ResourceManager.GetString("Eeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC has an error.
        /// </summary>
        internal static string Epc {
            get {
                return ResourceManager.GetString("Epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC fault contact open line.
        /// </summary>
        internal static string EpcOpenline {
            get {
                return ResourceManager.GetString("EpcOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC fault contact short circuit.
        /// </summary>
        internal static string EpcShortcut {
            get {
                return ResourceManager.GetString("EpcShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion card error.
        /// </summary>
        internal static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External audio input error.
        /// </summary>
        internal static string ExternAudioLine {
            get {
                return ResourceManager.GetString("ExternAudioLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External audio input Open line.
        /// </summary>
        internal static string ExternAudioOpenline {
            get {
                return ResourceManager.GetString("ExternAudioOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External audio input Short circuit.
        /// </summary>
        internal static string ExternAudioShortcut {
            get {
                return ResourceManager.GetString("ExternAudioShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External fault contact activated.
        /// </summary>
        internal static string ExternError {
            get {
                return ResourceManager.GetString("ExternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External fault contact Open line.
        /// </summary>
        internal static string ExternOpenline {
            get {
                return ResourceManager.GetString("ExternOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External fault contact Short circuit.
        /// </summary>
        internal static string ExternShortcut {
            get {
                return ResourceManager.GetString("ExternShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch dog error occurred.
        /// </summary>
        internal static string HwWdog {
            get {
                return ResourceManager.GetString("HwWdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance deviation at 1kHz on Line A.
        /// </summary>
        internal static string ImpDev1KhzA {
            get {
                return ResourceManager.GetString("ImpDev1KhzA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance deviation at 1kHz on Line B.
        /// </summary>
        internal static string ImpDev1KhzB {
            get {
                return ResourceManager.GetString("ImpDev1KhzB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance deviation at 20kHz.
        /// </summary>
        internal static string ImpDev22Khz {
            get {
                return ResourceManager.GetString("ImpDev22Khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230Vac mains power error.
        /// </summary>
        internal static string MainPower230V {
            get {
                return ResourceManager.GetString("MainPower230V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230Vac fault contact activated.
        /// </summary>
        internal static string MainsFuse {
            get {
                return ResourceManager.GetString("MainsFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230Vac fault contact Open line.
        /// </summary>
        internal static string MainsFuseOpenline {
            get {
                return ResourceManager.GetString("MainsFuseOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230Vac fault contact Short circuit.
        /// </summary>
        internal static string MainsFuseShortcut {
            get {
                return ResourceManager.GetString("MainsFuseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic capsule connection open line.
        /// </summary>
        internal static string MicCapOpenLine {
            get {
                return ResourceManager.GetString("MicCapOpenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic capsule connection short circuit.
        /// </summary>
        internal static string MicCapShortcut {
            get {
                return ResourceManager.GetString("MicCapShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Mic/Line panel bus 1.
        /// </summary>
        internal static string MicLineBus1 {
            get {
                return ResourceManager.GetString("MicLineBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Mic/Line panel bus 2.
        /// </summary>
        internal static string MicLineBus2 {
            get {
                return ResourceManager.GetString("MicLineBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic push to talk button is requested.
        /// </summary>
        internal static string MicRequest {
            get {
                return ResourceManager.GetString("MicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card 1 error.
        /// </summary>
        internal static string Mp31 {
            get {
                return ResourceManager.GetString("Mp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card 2 error.
        /// </summary>
        internal static string Mp32 {
            get {
                return ResourceManager.GetString("Mp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup amplifier.
        /// </summary>
        internal static string NoBackup {
            get {
                return ResourceManager.GetString("NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line A found.
        /// </summary>
        internal static string OpenlineA {
            get {
                return ResourceManager.GetString("OpenlineA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open line B found.
        /// </summary>
        internal static string OpenlineB {
            get {
                return ResourceManager.GetString("OpenlineB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evac panel com error.
        /// </summary>
        internal static string PanelTxIsr {
            get {
                return ResourceManager.GetString("PanelTxIsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com error on panel bus 1.
        /// </summary>
        internal static string Rs485FpBus1 {
            get {
                return ResourceManager.GetString("Rs485FpBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com error on panel bus 2.
        /// </summary>
        internal static string Rs485FpBus2 {
            get {
                return ResourceManager.GetString("Rs485FpBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com error on ESC link connection.
        /// </summary>
        internal static string Rs485MasterSlave {
            get {
                return ResourceManager.GetString("Rs485MasterSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit found on line A.
        /// </summary>
        internal static string ShortcutA {
            get {
                return ResourceManager.GetString("ShortcutA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit found on line B.
        /// </summary>
        internal static string ShortcutB {
            get {
                return ResourceManager.GetString("ShortcutB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short to Earth found.
        /// </summary>
        internal static string ShortcutToEarth {
            get {
                return ResourceManager.GetString("ShortcutToEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com error to Slave unit.
        /// </summary>
        internal static string SlaveComInterface {
            get {
                return ResourceManager.GetString("SlaveComInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave unit has errors.
        /// </summary>
        internal static string SlaveErrorsAvailable {
            get {
                return ResourceManager.GetString("SlaveErrorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital audio ch1 error on ESC unit link.
        /// </summary>
        internal static string SlaveSpdif1 {
            get {
                return ResourceManager.GetString("SlaveSpdif1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital audio ch2 error on ESC unit link.
        /// </summary>
        internal static string SlaveSpdif2 {
            get {
                return ResourceManager.GetString("SlaveSpdif2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48Vdc backup power error.
        /// </summary>
        internal static string SparePower48V {
            get {
                return ResourceManager.GetString("SparePower48V", resourceCulture);
            }
        }
    }
}
