//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UcLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UcLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.UserControls.UcLog", typeof(UcLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmpDefect.
        /// </summary>
        public static string AmpDefect {
            get {
                return ResourceManager.GetString("AmpDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier {0}.
        /// </summary>
        public static string Amplifier {
            get {
                return ResourceManager.GetString("Amplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Amplifier {0}.
        /// </summary>
        public static string BackupAmplifier {
            get {
                return ResourceManager.GetString("BackupAmplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string chDateTime {
            get {
                return ResourceManager.GetString("chDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string chDescription {
            get {
                return ResourceManager.GetString("chDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string chDetail {
            get {
                return ResourceManager.GetString("chDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string chDevice {
            get {
                return ResourceManager.GetString("chDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string chId {
            get {
                return ResourceManager.GetString("chId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Open.
        /// </summary>
        public static string chIsOpen {
            get {
                return ResourceManager.GetString("chIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error status.
        /// </summary>
        public static string chStatus {
            get {
                return ResourceManager.GetString("chStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC Unit.
        /// </summary>
        public static string chUnit {
            get {
                return ResourceManager.GetString("chUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com1 Interface.
        /// </summary>
        public static string Com1Interface {
            get {
                return ResourceManager.GetString("Com1Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com2 Interface.
        /// </summary>
        public static string Com2Interface {
            get {
                return ResourceManager.GetString("Com2Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Err.-DSP.
        /// </summary>
        public static string Dsp {
            get {
                return ResourceManager.GetString("Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Err.-E2Pr.
        /// </summary>
        public static string Eeprom {
            get {
                return ResourceManager.GetString("Eeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC Error.
        /// </summary>
        public static string Epc {
            get {
                return ResourceManager.GetString("Epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC Open line.
        /// </summary>
        public static string EpcOpenline {
            get {
                return ResourceManager.GetString("EpcOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC Short circuit.
        /// </summary>
        public static string EpcShortcut {
            get {
                return ResourceManager.GetString("EpcShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ErrorContent {
            get {
                return ResourceManager.GetString("ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier {0} defect.
        /// </summary>
        public static string ErrorLogAmpDetail {
            get {
                return ResourceManager.GetString("ErrorLogAmpDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier + Spare Amplifier Error.
        /// </summary>
        public static string ErrorLogAmplifier {
            get {
                return ResourceManager.GetString("ErrorLogAmplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Errors - possible Errors from external connected devices.
        /// </summary>
        public static string ErrorLogExternal {
            get {
                return ResourceManager.GetString("ErrorLogExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP 17-32 expansion panel error.
        /// </summary>
        public static string ErrorLogFp17ExpansionPanel {
            get {
                return ResourceManager.GetString("ErrorLogFp17ExpansionPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP 17-32  microphone request error.
        /// </summary>
        public static string ErrorlogFp17MicError {
            get {
                return ResourceManager.GetString("ErrorlogFp17MicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Errors - possible Errors in the device.
        /// </summary>
        public static string ErrorLogInternalerrors {
            get {
                return ResourceManager.GetString("ErrorLogInternalerrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone capsule 17-32 open line.
        /// </summary>
        public static string ErrorLogMic17Open {
            get {
                return ResourceManager.GetString("ErrorLogMic17Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone capsule 17-32 shortcut.
        /// </summary>
        public static string ErrorLogMic17Short {
            get {
                return ResourceManager.GetString("ErrorLogMic17Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP 1-16  microphone request line error.
        /// </summary>
        public static string ErrorlogMicRequest {
            get {
                return ResourceManager.GetString("ErrorlogMicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone capsule 1-16 open line.
        /// </summary>
        public static string ErrorLogMicrophoneOpen {
            get {
                return ResourceManager.GetString("ErrorLogMicrophoneOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone capsule 1-16 shortcut.
        /// </summary>
        public static string ErrorLogMicrophoneShort {
            get {
                return ResourceManager.GetString("ErrorLogMicrophoneShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave Communication Error 1-16.
        /// </summary>
        public static string ErrorlogSlaveError {
            get {
                return ResourceManager.GetString("ErrorlogSlaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave Communication Error 17-32.
        /// </summary>
        public static string ErrorlogSlaveError17 {
            get {
                return ResourceManager.GetString("ErrorlogSlaveError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker line {0} error.
        /// </summary>
        public static string ErrorLogSpeakerSpeaker {
            get {
                return ResourceManager.GetString("ErrorLogSpeakerSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string ErrorLogWindowClearList {
            get {
                return ResourceManager.GetString("ErrorLogWindowClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP 1-16 expansion panel error.
        /// </summary>
        public static string ErrorLopExpPanelError {
            get {
                return ResourceManager.GetString("ErrorLopExpPanelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC Unit {0}.
        /// </summary>
        public static string EscUnitName {
            get {
                return ResourceManager.GetString("EscUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Panel {0}.
        /// </summary>
        public static string Evacuation {
            get {
                return ResourceManager.GetString("Evacuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        public static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc external {0}.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Audio Line.
        /// </summary>
        public static string ExternAudioLine {
            get {
                return ResourceManager.GetString("ExternAudioLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Audio Open line.
        /// </summary>
        public static string ExternAudioOpenline {
            get {
                return ResourceManager.GetString("ExternAudioOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Audio Short circuit.
        /// </summary>
        public static string ExternAudioShortcut {
            get {
                return ResourceManager.GetString("ExternAudioShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Error.
        /// </summary>
        public static string ExternError {
            get {
                return ResourceManager.GetString("ExternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Open line.
        /// </summary>
        public static string ExternOpenline {
            get {
                return ResourceManager.GetString("ExternOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Short circuit.
        /// </summary>
        public static string ExternShortcut {
            get {
                return ResourceManager.GetString("ExternShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string FaultConfirmed {
            get {
                return ResourceManager.GetString("FaultConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string FaultReseted {
            get {
                return ResourceManager.GetString("FaultReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string FaultSet {
            get {
                return ResourceManager.GetString("FaultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDS interface {0}.
        /// </summary>
        public static string Fds {
            get {
                return ResourceManager.GetString("Fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Panel {0}.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Err.-WDOG.
        /// </summary>
        public static string HwWdog {
            get {
                return ResourceManager.GetString("HwWdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Imp. Dev. 1kHz.
        /// </summary>
        public static string ImpDev1KhzA {
            get {
                return ResourceManager.GetString("ImpDev1KhzA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B: Imp. Dev. 1kHz.
        /// </summary>
        public static string ImpDev1KhzB {
            get {
                return ResourceManager.GetString("ImpDev1KhzB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp. Dev. 20kHz.
        /// </summary>
        public static string ImpDev22Khz {
            get {
                return ResourceManager.GetString("ImpDev22Khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc internal {0}.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Power 230V.
        /// </summary>
        public static string MainPower230V {
            get {
                return ResourceManager.GetString("MainPower230V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains Fuse.
        /// </summary>
        public static string MainsFuse {
            get {
                return ResourceManager.GetString("MainsFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains Fuse Open line.
        /// </summary>
        public static string MainsFuseOpenline {
            get {
                return ResourceManager.GetString("MainsFuseOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains Fuse Short circuit.
        /// </summary>
        public static string MainsFuseShortcut {
            get {
                return ResourceManager.GetString("MainsFuseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic Cap Open Line.
        /// </summary>
        public static string MicCapOpenLine {
            get {
                return ResourceManager.GetString("MicCapOpenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic Cap Shortcut.
        /// </summary>
        public static string MicCapShortcut {
            get {
                return ResourceManager.GetString("MicCapShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicLine Bus 1.
        /// </summary>
        public static string MicLineBus1 {
            get {
                return ResourceManager.GetString("MicLineBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicLine Bus 2.
        /// </summary>
        public static string MicLineBus2 {
            get {
                return ResourceManager.GetString("MicLineBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic Request.
        /// </summary>
        public static string MicRequest {
            get {
                return ResourceManager.GetString("MicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Err.-Data 1.
        /// </summary>
        public static string Mp31 {
            get {
                return ResourceManager.GetString("Mp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.Err.-Data 2.
        /// </summary>
        public static string Mp32 {
            get {
                return ResourceManager.GetString("Mp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Backup Amplifier.
        /// </summary>
        public static string NO_BACKUP {
            get {
                return ResourceManager.GetString("NO_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string NoBackup {
            get {
                return ResourceManager.GetString("NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Self Healed.
        /// </summary>
        public static string NotSelfHealth {
            get {
                return ResourceManager.GetString("NotSelfHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Open line.
        /// </summary>
        public static string OpenlineA {
            get {
                return ResourceManager.GetString("OpenlineA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B: Open line.
        /// </summary>
        public static string OpenlineB {
            get {
                return ResourceManager.GetString("OpenlineB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel-Tx-ISR.
        /// </summary>
        public static string PanelTxIsr {
            get {
                return ResourceManager.GetString("PanelTxIsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485 Bus 1.
        /// </summary>
        public static string Rs485FpBus1 {
            get {
                return ResourceManager.GetString("Rs485FpBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485 Bus 2.
        /// </summary>
        public static string Rs485FpBus2 {
            get {
                return ResourceManager.GetString("Rs485FpBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485 Master/Slave.
        /// </summary>
        public static string Rs485MasterSlave {
            get {
                return ResourceManager.GetString("Rs485MasterSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Healed.
        /// </summary>
        public static string SelfHealth {
            get {
                return ResourceManager.GetString("SelfHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut speakerline A.
        /// </summary>
        public static string SHORTCUT_A {
            get {
                return ResourceManager.GetString("SHORTCUT_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Short circuit.
        /// </summary>
        public static string ShortcutA {
            get {
                return ResourceManager.GetString("ShortcutA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B: Short circuit.
        /// </summary>
        public static string ShortcutB {
            get {
                return ResourceManager.GetString("ShortcutB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short circuit to Earth.
        /// </summary>
        public static string ShortcutToEarth {
            get {
                return ResourceManager.GetString("ShortcutToEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC Slave {0}.
        /// </summary>
        public static string Slave {
            get {
                return ResourceManager.GetString("Slave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave Com Interface.
        /// </summary>
        public static string SlaveComInterface {
            get {
                return ResourceManager.GetString("SlaveComInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave SPDIF 1.
        /// </summary>
        public static string SlaveSpdif1 {
            get {
                return ResourceManager.GetString("SlaveSpdif1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave SPDIF 2.
        /// </summary>
        public static string SlaveSpdif2 {
            get {
                return ResourceManager.GetString("SlaveSpdif2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Power 48V.
        /// </summary>
        public static string SparePower48V {
            get {
                return ResourceManager.GetString("SparePower48V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeakerline {0}.
        /// </summary>
        public static string Speakerline {
            get {
                return ResourceManager.GetString("Speakerline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Entero Emergency Evacuation system error has occured.
        /// </summary>
        public static string TrayErrorTitle {
            get {
                return ResourceManager.GetString("TrayErrorTitle", resourceCulture);
            }
        }
    }
}
