//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WhatIfs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WhatIfs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.UserControls.WhatIfs", typeof(WhatIfs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: Check if amplifier is still &apos;ON&apos;  (Green 230Vac and/or 48Vdc indicator) and not in protect mode (Yellow indicators). If not: contact your dealer. If yes: reset error and wait a few minutes;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string AmpDefect {
            get {
                return ResourceManager.GetString("AmpDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Com1Interface {
            get {
                return ResourceManager.GetString("Com1Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Com2Interface {
            get {
                return ResourceManager.GetString("Com2Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should perform a power cycle (230Vac and 48Vdc) to check if error returns..
        /// </summary>
        public static string Dsp {
            get {
                return ResourceManager.GetString("Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should perform a power cycle (230Vac and 48Vdc) to check if error returns..
        /// </summary>
        public static string Eeprom {
            get {
                return ResourceManager.GetString("Eeprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: ensure the EPC battery charger does not indicate any errors. If it does, contact your dealer. If it does not; reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Epc {
            get {
                return ResourceManager.GetString("Epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. There is probably a connection fault between devices..
        /// </summary>
        public static string EpcOpenline {
            get {
                return ResourceManager.GetString("EpcOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. There is probably a connection fault between devices..
        /// </summary>
        public static string EpcShortcut {
            get {
                return ResourceManager.GetString("EpcShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Expansion {
            get {
                return ResourceManager.GetString("Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ExternAudioLine {
            get {
                return ResourceManager.GetString("ExternAudioLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ExternAudioOpenline {
            get {
                return ResourceManager.GetString("ExternAudioOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ExternAudioShortcut {
            get {
                return ResourceManager.GetString("ExternAudioShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: ensure that the ESA amplifiers do not indicate a protection mode; If they do, contact your dealer. If they don&apos;t; reset error, if error returns, contact your dealer..
        /// </summary>
        public static string ExternError {
            get {
                return ResourceManager.GetString("ExternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. There is probably a connection fault between devices..
        /// </summary>
        public static string ExternOpenline {
            get {
                return ResourceManager.GetString("ExternOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. There is probably a connection fault between devices..
        /// </summary>
        public static string ExternShortcut {
            get {
                return ResourceManager.GetString("ExternShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should perform a power cycle (230Vac and 48Vdc) to check if error returns..
        /// </summary>
        public static string HwWdog {
            get {
                return ResourceManager.GetString("HwWdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a partial disconnected speaker or speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ImpDev1KhzA {
            get {
                return ResourceManager.GetString("ImpDev1KhzA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a partial disconnected speaker or speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ImpDev1KhzB {
            get {
                return ResourceManager.GetString("ImpDev1KhzB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a partial disconnected speaker or speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ImpDev22Khz {
            get {
                return ResourceManager.GetString("ImpDev22Khz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: the Entero ESC detected a 230Vac power loss. Check if all connections are ok and if other devices do not indicate 230Vac errors. Reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MainPower230V {
            get {
                return ResourceManager.GetString("MainPower230V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: ensure that the ESA amplifiers and EPC battery charger are powered from 230Vac; If not, contact your dealer. If yes; reset error, if error returns;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MainsFuse {
            get {
                return ResourceManager.GetString("MainsFuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: ensure that the ESA amplifiers and EPC battery charger are powered from 230Vac; If not, contact your dealer. If yes; reset error, if error returns;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MainsFuseOpenline {
            get {
                return ResourceManager.GetString("MainsFuseOpenline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error, if the error returns, contact your dealer. There is probably a connection fault between devices..
        /// </summary>
        public static string MainsFuseShortcut {
            get {
                return ResourceManager.GetString("MainsFuseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure the cable of the Fire Mic is connected &amp; not damaged (which can cause an open connection). Reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MicCapOpenLine {
            get {
                return ResourceManager.GetString("MicCapOpenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure the Microphone is properly fixed to the housing and does not show any signs of damage (which can cause an internal open connection). Reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MicCapShortcut {
            get {
                return ResourceManager.GetString("MicCapShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MicLineBus1 {
            get {
                return ResourceManager.GetString("MicLineBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MicLineBus2 {
            get {
                return ResourceManager.GetString("MicLineBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure the red Fire Mic is connected and does not show any signs of damage (which can cause a broken switch). Reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string MicRequest {
            get {
                return ResourceManager.GetString("MicRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should check if SD cards are properly inserted and do not contain corrupted files..
        /// </summary>
        public static string Mp31 {
            get {
                return ResourceManager.GetString("Mp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should check if SD cards are properly inserted and do not contain corrupted files..
        /// </summary>
        public static string Mp32 {
            get {
                return ResourceManager.GetString("Mp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: Check if amplifier is still &apos;ON&apos; (Green 230Vac and/or 48Vdc indicator) and not in protect mode (Yellow indicators). If not: contact your dealer. If yes: reset the error and wait a few minutes; Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string NoBackup {
            get {
                return ResourceManager.GetString("NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused an open/disconnected speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string OpenlineA {
            get {
                return ResourceManager.GetString("OpenlineA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused an open/disconnected speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string OpenlineB {
            get {
                return ResourceManager.GetString("OpenlineB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: reset error;  Acknowledge the error if it returns and contact your dealer. Dealer should perform a power cycle (230Vac and 48Vdc) to check if error returns..
        /// </summary>
        public static string PanelTxIsr {
            get {
                return ResourceManager.GetString("PanelTxIsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Rs485FpBus1 {
            get {
                return ResourceManager.GetString("Rs485FpBus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Rs485FpBus2 {
            get {
                return ResourceManager.GetString("Rs485FpBus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short or disconnection on this line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string Rs485MasterSlave {
            get {
                return ResourceManager.GetString("Rs485MasterSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short on the speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ShortcutA {
            get {
                return ResourceManager.GetString("ShortcutA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short on the speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ShortcutB {
            get {
                return ResourceManager.GetString("ShortcutB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a short to earth on the speaker line. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string ShortcutToEarth {
            get {
                return ResourceManager.GetString("ShortcutToEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on the link to a Slave ESC unit. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string SlaveComInterface {
            get {
                return ResourceManager.GetString("SlaveComInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: check slave unit for more details on the found error(s).
        /// </summary>
        public static string SlaveErrorsAvailable {
            get {
                return ResourceManager.GetString("SlaveErrorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on the link to a Slave ESC unit. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string SlaveSpdif1 {
            get {
                return ResourceManager.GetString("SlaveSpdif1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: make sure no construction took place or wiring changes have been made in the building which could have caused a failure on the link to a Slave ESC unit. Reset the error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string SlaveSpdif2 {
            get {
                return ResourceManager.GetString("SlaveSpdif2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action: the Entero ESC detected a 48Vdc power loss. Check if all connections are ok and if other devices do not indicate 48Vdc errors. Reset error;  Acknowledge the error if it returns and contact your dealer..
        /// </summary>
        public static string SparePower48V {
            get {
                return ResourceManager.GetString("SparePower48V", resourceCulture);
            }
        }
    }
}
