//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Communication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Communication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.View.Communication", typeof(Communication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string _commBlockTitle {
            get {
                return ResourceManager.GetString("_commBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string _commDisable {
            get {
                return ResourceManager.GetString("_commDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string _commEnable {
            get {
                return ResourceManager.GetString("_commEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicaton settings.
        /// </summary>
        public static string _commGroupConSettings {
            get {
                return ResourceManager.GetString("_commGroupConSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string _commPassword {
            get {
                return ResourceManager.GetString("_commPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string _commRefresh {
            get {
                return ResourceManager.GetString("_commRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string _nocomm {
            get {
                return ResourceManager.GetString("_nocomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial connection.
        /// </summary>
        public static string _serial {
            get {
                return ResourceManager.GetString("_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection (ctrl+n).
        /// </summary>
        public static string AddConnection {
            get {
                return ResourceManager.GetString("AddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add network connection.
        /// </summary>
        public static string AddNetworkConnection {
            get {
                return ResourceManager.GetString("AddNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add usb connection.
        /// </summary>
        public static string AddUsbConnection {
            get {
                return ResourceManager.GetString("AddUsbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced mode.
        /// </summary>
        public static string AdvancedMode {
            get {
                return ResourceManager.GetString("AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect/Disconnect.
        /// </summary>
        public static string btnInstallMode {
            get {
                return ResourceManager.GetString("btnInstallMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string ClearChangeList {
            get {
                return ResourceManager.GetString("ClearChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com Port.
        /// </summary>
        public static string ComConnect {
            get {
                return ResourceManager.GetString("ComConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to: {0}.
        /// </summary>
        public static string ConnectionTo {
            get {
                return ResourceManager.GetString("ConnectionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Entero VA system is calibrated; clear &apos;Slave calibration&apos; on the Master ESC unit to avoid communication interrupts by the Master. .
        /// </summary>
        public static string ConnectionWarning {
            get {
                return ResourceManager.GetString("ConnectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget to re-calibrate the Slaves when configuration is finished..
        /// </summary>
        public static string ConnectionWarningLine2 {
            get {
                return ResourceManager.GetString("ConnectionWarningLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ConnectionWarningTitle {
            get {
                return ResourceManager.GetString("ConnectionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name.
        /// </summary>
        public static string ErrorModuleName {
            get {
                return ResourceManager.GetString("ErrorModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring mode OFF.
        /// </summary>
        public static string InstallModeOff {
            get {
                return ResourceManager.GetString("InstallModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install mode on.
        /// </summary>
        public static string InstallModeOn {
            get {
                return ResourceManager.GetString("InstallModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering password.
        /// </summary>
        public static string InstallModePasswordEnter {
            get {
                return ResourceManager.GetString("InstallModePasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Isdisp {
            get {
                return ResourceManager.GetString("Isdisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring mode.
        /// </summary>
        public static string MonitoringMode {
            get {
                return ResourceManager.GetString("MonitoringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string NetConnect {
            get {
                return ResourceManager.GetString("NetConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No communication variant selected.
        /// </summary>
        public static string NoCommunicationSelected {
            get {
                return ResourceManager.GetString("NoCommunicationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No com port available.
        /// </summary>
        public static string NoComPort {
            get {
                return ResourceManager.GetString("NoComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no response from mcu.
        /// </summary>
        public static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packets to be send (advanced).
        /// </summary>
        public static string PacketsHeader {
            get {
                return ResourceManager.GetString("PacketsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PasswordChangeCaption {
            get {
                return ResourceManager.GetString("PasswordChangeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure changing the password?.
        /// </summary>
        public static string PasswordChangeQuestion {
            get {
                return ResourceManager.GetString("PasswordChangeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Ok.
        /// </summary>
        public static string PasswordOk {
            get {
                return ResourceManager.GetString("PasswordOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove connection .
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry enter.
        /// </summary>
        public static string RetryEnter {
            get {
                return ResourceManager.GetString("RetryEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued data.
        /// </summary>
        public static string UnboundData {
            get {
                return ResourceManager.GetString("UnboundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitId {
            get {
                return ResourceManager.GetString("UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, data queued for sending. Switch tab to clear..
        /// </summary>
        public static string WarningQueuedData {
            get {
                return ResourceManager.GetString("WarningQueuedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong IP Address.
        /// </summary>
        public static string WrongIp {
            get {
                return ResourceManager.GetString("WrongIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string WrongPasswrd {
            get {
                return ResourceManager.GetString("WrongPasswrd", resourceCulture);
            }
        }
    }
}
