//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SendEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.View.SendEmail", typeof(SendEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings.
        /// </summary>
        public static string _emailBlockTitle {
            get {
                return ResourceManager.GetString("_emailBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string _emailDealerAddress {
            get {
                return ResourceManager.GetString("_emailDealerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        public static string _emailDealerContact {
            get {
                return ResourceManager.GetString("_emailDealerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string _emailDealerCountry {
            get {
                return ResourceManager.GetString("_emailDealerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string _emailDealerEmail {
            get {
                return ResourceManager.GetString("_emailDealerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string _emailDealerName {
            get {
                return ResourceManager.GetString("_emailDealerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string _emailDealerPhone {
            get {
                return ResourceManager.GetString("_emailDealerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string _emailDealerPlace {
            get {
                return ResourceManager.GetString("_emailDealerPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string _emailDealerZip {
            get {
                return ResourceManager.GetString("_emailDealerZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delear details.
        /// </summary>
        public static string _emailGroupDealer {
            get {
                return ResourceManager.GetString("_emailGroupDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details.
        /// </summary>
        public static string _emailGroupProject {
            get {
                return ResourceManager.GetString("_emailGroupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivers.
        /// </summary>
        public static string _emailGroupReceiver {
            get {
                return ResourceManager.GetString("_emailGroupReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string _emailGroupSender {
            get {
                return ResourceManager.GetString("_emailGroupSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email.
        /// </summary>
        public static string _emailGroupTest {
            get {
                return ResourceManager.GetString("_emailGroupTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string _emailProjectAddress {
            get {
                return ResourceManager.GetString("_emailProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        public static string _emailProjectContact {
            get {
                return ResourceManager.GetString("_emailProjectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string _emailProjectCountry {
            get {
                return ResourceManager.GetString("_emailProjectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string _emailProjectEmail {
            get {
                return ResourceManager.GetString("_emailProjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string _emailProjectName {
            get {
                return ResourceManager.GetString("_emailProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string _emailProjectPhone {
            get {
                return ResourceManager.GetString("_emailProjectPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string _emailProjectPlace {
            get {
                return ResourceManager.GetString("_emailProjectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string _emailProjectZip {
            get {
                return ResourceManager.GetString("_emailProjectZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver .
        /// </summary>
        public static string _emailReceiver {
            get {
                return ResourceManager.GetString("_emailReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup copy to Bose.
        /// </summary>
        public static string _emailReceiverBackup {
            get {
                return ResourceManager.GetString("_emailReceiverBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string _emailReceiverCountry {
            get {
                return ResourceManager.GetString("_emailReceiverCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From name.
        /// </summary>
        public static string _emailSenderDisplay {
            get {
                return ResourceManager.GetString("_emailSenderDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string _emailSenderFrom {
            get {
                return ResourceManager.GetString("_emailSenderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string _emailSenderPassword {
            get {
                return ResourceManager.GetString("_emailSenderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP port.
        /// </summary>
        public static string _emailSenderSMTPport {
            get {
                return ResourceManager.GetString("_emailSenderSMTPport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server.
        /// </summary>
        public static string _emailSenderSMTPserver {
            get {
                return ResourceManager.GetString("_emailSenderSMTPserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP settings.
        /// </summary>
        public static string _emailSenderSMTPSetttings {
            get {
                return ResourceManager.GetString("_emailSenderSMTPSetttings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Enabled.
        /// </summary>
        public static string _emailSenderSSL {
            get {
                return ResourceManager.GetString("_emailSenderSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string _emailSenderUserName {
            get {
                return ResourceManager.GetString("_emailSenderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string _emailTestAttachment {
            get {
                return ResourceManager.GetString("_emailTestAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string _emailTestBody {
            get {
                return ResourceManager.GetString("_emailTestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse...
        /// </summary>
        public static string _emailTestBrowse {
            get {
                return ResourceManager.GetString("_emailTestBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string _emailTestSendMail {
            get {
                return ResourceManager.GetString("_emailTestSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string _emailTestSubject {
            get {
                return ResourceManager.GetString("_emailTestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was send.
        /// </summary>
        public static string _messagewassend {
            get {
                return ResourceManager.GetString("_messagewassend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string AddEmail {
            get {
                return ResourceManager.GetString("AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email has been send.
        /// </summary>
        public static string MailSendMessageBox {
            get {
                return ResourceManager.GetString("MailSendMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email .
        /// </summary>
        public static string MailSendMessageBoxHeader {
            get {
                return ResourceManager.GetString("MailSendMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveEmail {
            get {
                return ResourceManager.GetString("RemoveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an test email.
        /// </summary>
        public static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all neccesarily fields were filed in (all sending details are necessarily and at least one receiver).
        /// </summary>
        public static string TestMailError {
            get {
                return ResourceManager.GetString("TestMailError", resourceCulture);
            }
        }
    }
}
